---
title: "数据库基础知识"
author: ""
date: "2020-03"
output:
  bookdown::html_document2:
    number_sections: true
    seq_numbering: true
    fig_caption: true
    highlight: haddock
    theme: null
    md_extensions: +east_asian_line_breaks
    keep_md: true
    toc: false
    pandoc_args: ["--filter", "pandoc-crossref", "-M", "eqnPrefix="]
  bookdown::word_document2:
    fig_caption: true
    reference_docx: ./style/word-styles-02.docx
    md_extensions: +east_asian_line_breaks
    pandoc_args: ["--filter", "pandoc-crossref"]
  bookdown::pdf_document2:
    keep_tex: yes
    toc: false
    latex_engine: xelatex
    md_extensions: +east_asian_line_breaks
    pandoc_args: ["--listing", "--filter", "pandoc-crossref"]
css: ./style/markdown.css
autoEqnLabels: true
eqnPrefixTemplate: ($$i$$)
linkReferences: true
bibliography: Bibfile.bib
csl: ./style/chinese-gb7714-2005-numeric.csl
link-citations: true
---

# 绪论
## 数据库系统概述
### 四个基本概念
#### 数据（Data）
1. 数据（Data）是数据库中存储的基本对象
2. 数据的定义：描述事物的符号记录
3. 数据的种类：文本、图形、图像、音频、视频等
4. 数据的特点：数据与其语义是不可分的
#### 数据库（Database）
1. 数据库的定义：
数据库（Database，简称DB）是长期存储在计算机内、有组织的、可共享的大量数据的集合。
2. 数据库的基本特征
     * 数据按一定的数据模型组织、描述和储存
    * 可为各种用户共享
    * 冗余度较小
    * 数据独立性较高
    * 易扩展
#### 数据库管理系统（DBMS）
1. 概念
    * 位于用户与操作系统之间的一层数据管理软件
    * 是基础软件，是一个大型复杂的软件系统
2. 用途
    * 科学地组织和存储数据、高效地获取和维护数据
3. 功能
  * 数据定义功能
    * 提供数据定义语言（DDL） 
    * 定义数据库中的数据对象
   * 数据组织、存储和管理
     * 分类组织、存储和管理各种数据
     * 确定组织数据的文件结构和存取方式
     * 实现数据之间的联系
     * 提供多种存取方法提高存取效率
  * 数据操纵功能
    * 提供数据操纵语言（DML）
    * 实现对数据库的基本操作（查询、插入、删除和修改）
  * 数据库的事务管理和运行管理
    * 数据库在建立、运行和维护时由DBMS统一管理和控制
    * 保证数据的安全性、完整性、多用户对数据的并发使用
    * 发生故障后的系统恢复
  * 数据库的建立和维护功能(实用程序)
    * 数据库初始数据装载转换
    * 数据库转储
    * 介质故障恢复
    * 数据库的重组织
    * 性能监视分析等
  * 其他功能
    * DBMS与网络中其它软件系统的通信
    * 两个DBMS系统的数据转换
    * 异构数据库之间的互访和互操作

#### 数据库系统（DBS）
1. 概念
在计算机系统中引入数据库后的系统构成
2. 数据库系统的构成
    * 数据库
    * 数据库管理系统（及其开发工具）
    * 应用系统
    * 数据库管理员
### 数据管理技术的产生和发展
1. 数据管理的概念
    * 对数据进行分类、组织、编码、存储、检索和维护
    * 数据处理的中心问题
2. 数据管理技术的发展过程
  * 人工管理阶段
  * 文件系统阶段
  * 数据库系统阶段
     * 时期
  20世纪60年代以来
    * 产生的背景
      * 应用背景   —— 大规模管理
      * 硬件背景 —— 大容量磁盘、磁盘阵列
      * 软件背景 —— 有数据库管理系统
      * 处理方式 —— 联机实时处理，分布处理，批处理
### 数据库系统的特点
1. 数据结构化
  * **整体数据的结构化**是数据库的主要特征之一
  * 整体结构化
  * 数据库中实现的是数据的真正结构化
    * 数据的结构用**数据模型**描述，无需程序定义和解释
    * 数据可以**变长**
    * 数据的最小存取单位是**数据项**
2. 数据的共享性高，冗余度低，易扩充
数据库系统从整体角度看待和描述数据，数据面向整个系统，可以被多个用户、多个应用共享使用。

3. 数据独立性高
  * 物理独立性
  指用户的应用程序与存储在磁盘上的数据库中数据是相互独立的。当数据的物理存储改变了，应用程序不用改变。
  * 逻辑独立性
  指用户的应用程序与数据库的逻辑结构是相互独立的。数据的逻辑结构改变了，用户程序也可以不变
  * 数据独立性是由DBMS的二级映像功能来保证的
4. 数据由DBMS统一管理和控制

## 数据模型
### 两大类数据模型
1. 在数据库中用数据模型这个工具来**抽象**、**表示**和**处理**现实世界中的数据和信息。
2. 通俗地讲数据模型就是**现实世界的模拟**
3. 数据模型应满足三方面要求
   * 能比较**真实**地模拟现实世界
   * **容易**为人做**理解**
   * 便于在计算机上实现
4. 数据模型分为两类（分属两个不同的层次）
   1. **概念模型**，也称信息模型，它是按用户的观点来对数据和信息建模，用于数据库设计。
   2. **逻辑模型和物理模型**
    * 逻辑模型主要包括网状模型、层次模型、关系模型、面向对象模型等，按计算机系统的观点对数据建模，用于DBMS实现
    * 物理模型是对数据最底层的抽象，描述数据在系统内部的表示方式和存取方法，在磁盘或磁带上的存储方式和存取方法。
5. 客观对象的抽象过程——**两步抽象**
    * 现实世界中的客观对象抽象为概念模型
    * 把概念模型转换为某一DBMS支持的数据模型
### 数据模型的组成要素
#### 数据结构
1. 数据结构的概念
描述数据库的组成对象，以及对象之间的联系
2. 描述的内容
  * 与数据烈性、内容、性质有关的对象
  * 与数据之间联系有关的对象
3. 数据结构是对系统静态特性的描述
#### 数据操作
1. 数据操作
对数据库中各种对象(型)的实例(值)允许执行的**操作**及有关的**操作规则**
2. 数据操作的类型
  * 查询
  * 更新（包括插入、删除、修改）
3. 数据模型对操作的定义
4. 数据操作是对系统动态特性的描述
#### 完整性约束条件
1. 数据的完整性约束条件
  * 一组完整性规则的集合。
  * 完整性规则：给定的数据模型中数据及其联系所具有的制约和储存规则
  * 用以限定符合数据模型的数据库状态以及状态的变化，以保证数据的正确、有效、相容。
2. 数据模型对完整性约束条件的定义
  * 反映和规定本**数据模型**必须遵守的**基本的通用的**完整性约束条件。例如在关系模型中，任何关系必须满足实体完整性和参照完整性两个条件。
  * 提供定义完整性约束条件的机制，以反映**具体应用**所涉及的数据必须遵守的特定的语义约束条件。
### 概念模型
1. 概念模型的用途
  * 概念模型用于信息世界的建模
  * 是现实世界到机器世界的一个中间层次
  * 是数据库设计的有力工具
  * 数据库设计人员和用户之间进行交流的语言
#### 信息世界中的基本概念
1. 实体（Entity）
客观存在并可相互区别的事物称为实体。
可以是具体的人、事、物或抽象的概念。
2. 属性（Attribute）
实体所具有的某一特性称为属性。
一个实体可以由若干个属性来刻画。  
3. 码（Key）
   唯一标识实体的属性集称为码。
4. 域（Domain）
属性的取值范围称为该属性的域。 
5. 实体型（Entity Type）
用实体名及其属性名集合来抽象和刻画同类实体称为实体型。
6. 实体集（Entity Set）
同一类型实体的集合称为实体集
7. 联系（Relationship）
  * 现实世界中事物内部以及事物之间的联系在信息世界中反映为实体内部的联系和实体之间的联系。
  * **实体内部**的联系通常是指组成实体的各属性之间的联系
  * **实体之间**的联系通常是指不同实体集之间的联系
#### 两个实体型之间的联系
1. 一对一联系（1：1）
  * 实例：一个班级只有一个正班长
  * 定义：如果对于实体集A中的每一个实体，实体集B中至多一个（也可以没有）实体与之联系，反之亦然，**则称实体集A与实体集B具有一对一联系**，记为1：1
2. 一对多联系（1：n）
   * 实例：一个班级中有若干个学生；每个学生只在一个班级中学习。
   * 定义：如果对于实体集A中的每一个实体，实体集B中有n个实体（n≥0）与之联系，反之，对于实体集B中的每一个实体，实体集A中至多只有一个实体与之联系，则称**实体集A与实体集B**有一对多联系，记为1:n
3. 多对多联系（m：n）
   * 实例：课程与学生之间的联系：一门课程同时有若干个学生选修；一个学生可以同时选修多门课程
   * 定义：如果对于实体集A中的每一个实体，实体集B中有n个实体（n≥0）与之联系，反之，对于实体集B中的每一个实体，实体集A中也有m个实
体（m≥0）与之联系，则称实体集A与实体B具有多对多联系，记为m:n

#### 两个以上实体型之间的联系
1. 两个以上实体型之间一对多联系
  * 定义:实体型E1，E2，...，Ek，(1)对于实体型Ej（j=1，2，...，i-1，i+1，...，n）中的给定实体，最多只和Ei中的一个实体相联系；(2)对于Ei中的一个实体, 和Ej中的n(n>=0)个实体相联系；则我们说Ei与E1，E2，...，Ei-1，Ei+1，...，Ek之间的联系是一对多的
  * 实例：课程、教师与参考书三个实体型。一门课程可以有若干个教师讲授，使用若干本参考书;每一个教师只讲授一门课程;每一本参考书只供一门课程使用
2.  两个以上实体型之间一对一联系
  * 定义:若实体型E1，E2，...，Ek，(1)对于实体型Ej（j=1，2，...，i-1，i+1，...，n）中的给定实体，最多只和Ei中的一个实体相联系；(2)对于实体型Ei中的给定实体，和Ej中的n个(n>=0)实体相联系，则我们说Ei与E1，E2，...，Ei-1，Ei+1，...，Ek之间的联系是一对多的。
  * 实例：班级、班长与班主任三个实体型。一个班级有且只有一个班长，有且只有一个班主任;一个班长只管一个班级;一个班主任只管一个班级。
3.  两个以上实体型之间多对多联系
  * 定义:实体型E1，E2，...，Ek，(1)对于实体型Ej（j=1，2，...，i-1，i+1，...，k）中的给定实体，和Ei中的n(n>=0)个实体相联系；(2)对于实体型Ei中的给定实体，和Ei中的m(m>=0)个实体相联系；则我们说Ei与E1，E2，...，Ei-1，Ei+1，...，Ek之间的联系是多对多的
  * 实例：供应商、项目、零件三个实体型。一个供应商可以供给多个项目多种零件；每个项目可以使用多个供应商供应的零件；每种零件可由不同供应商供给。

#### 单个实体型内的联系
1. 同一实体集内的各实体之间的关系
  * 一对多联系；例如职工实体型内部具有领导与被领导的联系。
  * 一对一联系；职工实体型内部具有配偶的联系。
  * 多对多联系；零件实体型内部具有构成的联系。
#### 概念模型的一种表示方法
1. 实体——联系方法（E-R方法）
  * 用E-R图来描述现实世界的概念模型
  * E-R方法也称为E-R模型
2. E-R图
  * 实体型：用矩形表示，矩形框内写明实体名。
  * 属性：用椭圆形表示，并用无向边将其与相应的实体连接起来
  * 联系：用菱形表示，菱形框内写明联系名，并用无向边分别与有关实体连接起来，同时在无向边旁标上联系的类型（1:1、1:n或m:n）
3. 联系的属性：联系本身也是一种实体型，也可以有属性。如果一个联系具有属性，则这些属性也要用无向边与该联系连接起来 


