---
title: "数据库和SQL基础"
author: ""
date: "2019-04"
output:
  bookdown::html_document2:
    number_sections: true
    seq_numbering: true
    fig_caption: true
    highlight: haddock
    theme: null
    md_extensions: +east_asian_line_breaks
    keep_md: true
    toc: false
    pandoc_args: ["--filter", "pandoc-crossref", "-M", "eqnPrefix="]
  bookdown::word_document2:
    fig_caption: true
    reference_docx: ./style/word-styles-02.docx
    md_extensions: +east_asian_line_breaks
    pandoc_args: ["--filter", "pandoc-crossref"]
  bookdown::pdf_document2:
    keep_tex: yes
    toc: false
    latex_engine: xelatex
    md_extensions: +east_asian_line_breaks
    pandoc_args: ["--listing", "--filter", "pandoc-crossref"]
css: ./style/markdown.css
autoEqnLabels: true
eqnPrefixTemplate: ($$i$$)
linkReferences: true
bibliography: Bibfile.bib
csl: ./style/chinese-gb7714-2005-numeric.csl
link-citations: true
---

**TODO**


```{r setup, echo=F}
knitr::opts_knit$set(root.dir = getwd())
knitr::opts_chunk$set(echo = FALSE, results = 'hide')
knitr::opts_chunk$set(warning = FALSE, message=FALSE)
```

```{r prepare}
rm(list=ls())
options(digits=4)
options(scipen=100)
graphics.off()
Sys.setlocale("LC_ALL", "Chinese")
```

# R连接到数据库设置(勿改)

1. 运行 pgsql
2. 运行以下代码

```{r eval=T, echo=TRUE}
library(RPostgreSQL)
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, host='localhost', port='5432', 
                 dbname='dvdrental', user='postgres', password='postgres')
summary(con)
```
3. SQL 代码块

```{sql echo=T, connection=con}
*************第一部分 查询***************
SELECT first_name FROM customer;
/*查询customer表中的名字*/

SELECT DISTINCT city FROM city;
/*查询city表中的城市名称（过滤掉重复值）*/

SELECT first_name,last_name FROM customer ORDER BY first_name ASC;
/*查询customer表中的名字和姓氏，按照名字升序排列*/
SELECT first_name,last_name FROM customer ORDER BY first_name ASC,last_name DESC;
/*查询customer表中的名字和姓氏，按照名字升序排列,当名字相同，姓氏降序排列*/
SELECT first_name || ' ' || last_name AS full_name FROM customer ORDER BY full_name;
/*连接customer表中的名字和姓氏，以空格隔开，并重命名为"full_name"*/
```
4. 可以在R代码中使用SQL查询结果，增加 `output.var="film_result"`

```{sql echo=F, connection=con, output.var="film_result"}
select title, length from film limit 10;
```

```{r eval=T}
film_result[,2]
```

# 参考文献
[//]: # (\bibliography{Bibfile})
